### ISSUE TITLE
Linux: Selecting the correct libusb version

### ISSUE THREAD

**Issue by pthomas** [texane/stlink#113] opened 2012-11-01 23:02 UTC
This started as an issue, but the fix is easy so I figured I'd post it here because I don't know where it should go.

In Fedora there are 2 libusb versions, libusb and libusb1. stlink depends on libusb1 so Fedora users (and possibly other distros) just need to install that, 'yum install libusb1-devel', and then stlink should compile fine.

For all you googlers the error if you just have libusb is:
checking for USB... no
configure: error: **\* Required libusb-1.0 >= 1.0.0 not installed ***

thanks,
Paul

**Comment by xor-gate** [comment] 2016-05-03 14:37
Duplicate of #211

**Comment by Nightwalker-87** [comment] 2020-03-22 00:37
See also #211.

**Comment by Nightwalker-87** [comment] 2020-03-23 17:30
As of today this also applies to several linux/unix distributions namely:

- CentOS 6, 7, 8
- Debian 8, 9, 10, sid
- Fedora 30, 31, Rawhide
- NetBSD 7.2, 8.1, 9.0
- openSUSE Leap 15.1, Leap 15.2
- Ubuntu 14.04 LTS, 16.04 LTS, 18.04 LTS, 19.10

Other relevant distributions appear to have packages named `libusb-compat-0.1` or alike to distinguish from `libusb` packages based on version 1.0.x.

**Comment by Nightwalker-87** [comment] 2020-03-23 18:14
Closed by 10ae5294cd03aacfc07312010f026d3cb12ea56c.

**Closed by Nightwalker-87** 2020-03-23 18:14 UTC
Labels: code/feedback, dependency/libusb, general/documention, os/linux, status/resolved
