### ISSUE TITLE
STM32F103C8T6 doesn't flash

### ISSUE THREAD

**Issue by MartianZ** [texane/stlink#172] opened 2013-08-10 08:59 UTC
Hello!

I tried ST-LINK v2 to flash STM32F103C8T6, but I cannot flash my code to the chip and it gives me a weird error:

2013-08-10T16:52:48 INFO src/stlink-common.c: Loading device parameters....
2013-08-10T16:52:48 INFO src/stlink-common.c: Device connected is: F1 Medium-density device, id 0x20036410
2013-08-10T16:52:48 INFO src/stlink-common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0 bytes (0 KiB) in pages of 1024 bytes
stlink_sram_flash() == -1

The STM32F103C8T6 has 64KiB ROM but the st-flash and st-util display: Flash: 0 bytes (0 KiB) in pages of 1024 bytes

I tried to flash the STM32F103C8T6 on Windows with J-Link and it worked fine so I'm sure there is nothing wrong with my board.

**Comment by MightyPork** [comment] 2016-05-11 18:02
Did you ever find a solution to this? I'm having the same issue now and can't find anything useful on Google

**Comment by xor-gate** [comment] 2016-05-11 18:05
Reopening this issue,
Please provide some more info on your setup/issue as described here:
https://raw.githubusercontent.com/texane/stlink/master/.github/ISSUE_TEMPLATE.md

**Comment by MightyPork** [comment] 2016-05-11 22:24
I managed to fix it by trying random things in openocd, can't really say how. I tried 'stm32f1 unlock' or something like that, also erase. 
At any rate, st-flash now works as expected. Odd that it just printed 0 KB earlier as if that made any sense...

linux, stm32f103k8, stlink 1.2.0, stlink v2

**Comment by xor-gate** [comment] 2016-05-14 12:16
Hmm, doing random things will not make life easier for other people to search to reproduce it. I have seen similar issues when `st-info` is prints info with 0KB SRAM etc.

**Comment by MightyPork** [comment] 2016-05-14 12:18
I have two of those Chinese F103 modules, so I'll pay closer attention if I encounter the issue with the second one ;-)

**Comment by xor-gate** [comment] 2016-05-14 12:20
I will close this issue because you got it working "sort of". Feel free to open a new issue when there are still troubles. Of course with the appropriate level of details so people can point in the right direction and reproduce for themselves.

Thanks you for your feedback.

**Closed by xor-gate** 2016-05-14 12:21 UTC
Labels: bug, needs-feedback, target-stm32f1

**Comment by jeanthom** [comment] 2017-11-29 15:03
I got the same issue as MightyPork and solved it using OpenOCD :
```sh
$ openocd -f interface/stlink-v2.cfg -f target/stm32f1x.cfg
```
In OpenOCD's telnet session :
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> halt
target halted due to debug-request, current mode: Handler HardFault
xPSR: 0x01000003 pc: 0xfffffffe msp: 0xffffffdc
> stm32f1x unlock 0
Device Security Bit Set
target halted due to breakpoint, current mode: Handler HardFault
xPSR: 0x61000003 pc: 0x2000003a msp: 0xffffffdc
stm32x unlocked.
INFO: a reset or power cycle is required for the new settings to take effect.
```

I then unplugged the target, and plugged it back in. Flash size was correctly recognized in st-flash ! :)

**Comment by lucky62** [comment] 2018-02-13 16:57
Hello, I have the same issue:
```
2018-02-13T17:45:54 INFO src/stlink-usb.c: -- exit_dfu_mode
2018-02-13T17:45:54 INFO src/stlink-common.c: Loading device parameters....
2018-02-13T17:45:54 INFO src/stlink-common.c: Device connected is: F1 Medium-density device, id 0x20036410
2018-02-13T17:45:54 INFO src/stlink-common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0 bytes (0 KiB) in pages of 1024 bytes

```
Which tools I can run and what output will help to solve this issue?

Thanks

**Comment by jeanthom** [comment] 2018-02-13 17:00
Please read my message above. It explains all you need to do :-)

**Comment by lucky62** [comment] 2018-02-13 17:42
I tried this, but result is not as expected.

```
$ telnet 127.0.0.1 4444
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Open On-Chip Debugger
> halt
> stm32f1x unlock 0
device id = 0x20036410
STM32 flash size failed, probe inaccurate - assuming 128k flash
flash size = 128kbytes
Device Security Bit Set
target state: halted
target halted due to breakpoint, current mode: Thread 
xPSR: 0x61000000 pc: 0x2000003a msp: 0x20000688
stm32x unlocked.
INFO: a reset or power cycle is required for the new settings to take effect.
```
But Flash size is wrong. Should be 64K, not 128K.

```
$ ./st-info --probe
Found 1 stlink programmers
 serial: 573f7106493f56535432083f
openocd: "\x57\x3f\x71\x06\x49\x3f\x56\x53\x54\x32\x08\x3f"
  flash: 131072 (pagesize: 1024)
   sram: 20480
 chipid: 0x0410
  descr: F1 Medium-density device

```

**Comment by jeanthom** [comment] 2018-02-13 17:44
You are using a STM32F103CBT6, right ?

**Comment by lucky62** [comment] 2018-02-13 17:58
No, it is STM32F103C8.

**Comment by jeanthom** [comment] 2018-02-13 18:05
They're the same internally ;) That's why you get reports of 128K of flash on an STM32F103C**8**.

More infos : http://www.stm32duino.com/viewtopic.php?t=110

**Comment by lucky62** [comment] 2018-02-13 18:11
Hmm, I think my MCU has only 64K.

This line from openocd output (see above) can be a problem:
`STM32 flash size failed, probe inaccurate - assuming 128k flash`

Blinky example flashed to board is not working.

**Comment by Evgsurf** [comment] 2018-05-23 06:27
Hello guys. It lookes like I have the same problem with STM32F103C8T6.
I use ubuntu 16.04 64x 
I got st-link frim GIT and build it.
I build blink project by AC6 SystemWorkbench tool.
When I flash, I got Ok state, but chip does not work.

./st-flash write Probe.bin 0x8000000
st-flash 1.4.0-36-g0af68c0
2018-05-23T09:18:29 INFO common.c: Loading device parameters....
2018-05-23T09:18:29 INFO common.c: Device connected is: F1 Medium-density device, id 0x20036410
2018-05-23T09:18:29 INFO common.c: SRAM size: 0x5000 bytes (20 KiB), Flash: 0x20000 bytes (128 KiB) in pages of 1024 bytes
2018-05-23T09:18:29 INFO common.c: Attempting to write 3088 (0xc10) bytes to stm32 address: 134217728 (0x8000000)
Flash page at addr: 0x08000c00 erased
2018-05-23T09:18:29 INFO common.c: Finished erasing 4 pages of 1024 (0x400) bytes
2018-05-23T09:18:29 INFO common.c: Starting Flash write for VL/F0/F3/F1_XL core id
2018-05-23T09:18:29 INFO flash_loader.c: Successfully loaded flash loader in sram
  4/4 pages written
2018-05-23T09:18:30 INFO common.c: Starting verification of write complete
2018-05-23T09:18:30 INFO common.c: Flash written and verified! jolly good!

Info shows 128Kb (I bot chip with 64 only)
./st-info --probe
Found 1 stlink programmers
 serial: 303030303030303030303031
openocd: "\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x30\x31"
  flash: **131072** (pagesize: 1024)
   sram: 20480
 chipid: 0x0410
  descr: F1 Medium-density device

I tired to unlock by openocr and telnet and got result like lucky62.

At the moment I have no ideas what I have to do.

Best Regards
Evgeny

P.S. I am to newbie with chips, sorry if I ask to simple questions.

**Comment by YcSmile** [comment] 2019-05-26 13:49
same question.
sloved.i have modified as below in function <stlink_load_device_params> when read the chip flash size reg.i just run a stlink_reset before do that.
info:
./st-flash --version
v1.5.1-28-gd040db5
`
// file: common.c
// function : int stlink_load_device_params(stlink_t *sl)
    stlink_read_debug32(sl,(params->flash_size_reg) & ~3, &flash_size);
    if(flash_size == 0)
    {
        ILOG("*** Read Flash Chip Size Error *** \n");
        ILOG("*** Will Reset Chip and ReRead *** \n");
        stlink_reset(sl);    
        stlink_read_debug32(sl,(params->flash_size_reg) & ~3, &flash_size);
        if(flash_size != 0)
        {
            ILOG("*** ReRead Successed *** \n");
        }
        else{
            
            ILOG("*** ReRead Failed *** \n");
            ILOG("*** Exit *** \n");
            exit(1);
        }
    }
`

**Comment by YcSmile** [comment] 2019-05-26 13:51
same question.
sloved.i have modified as below in function <stlink_load_device_params> when read the chip flash size reg.i just run a stlink_reset before do that.
info:
./st-flash --version
v1.5.1-28-gd040db5
```
    // file: common.c
    // function : int stlink_load_device_params(stlink_t *sl)
    stlink_read_debug32(sl,(params->flash_size_reg) & ~3, &flash_size);
    if(flash_size == 0)
    {
        ILOG("*** Read Flash Chip Size Error *** \n");
        ILOG("*** Will Reset Chip and ReRead *** \n");
        stlink_reset(sl);    
        stlink_read_debug32(sl,(params->flash_size_reg) & ~3, &flash_size);
        if(flash_size != 0)
        {
            ILOG("*** ReRead Successed *** \n");
        }
        else{
            
            ILOG("*** ReRead Failed *** \n");
            ILOG("*** Exit *** \n");
            exit(1);
        }
    }
```

**Comment by Nightwalker-87** [comment] 2020-02-25 18:31
Issue has been reviewed and is now permanently closed.
Please also keep in mind that this is not an openocd support forum.
Any further questions or feedback on this **must** go into a new ticket.
